GaiZhenbiao/ChuanhuChatGPT

- ChuanhuChatbot.py
> fix bugs and add "reduce token" function, optimize statistics

- ChuanhuChatbot.py
> 新增输入key，取消api全局设置

- ChuanhuChatbot.py
> chore: 遮挡预设的api_key

- .github/workflows/Docker Images.yml
- Dockerfile
we need to add three secrets in the repository settings.
MY_TOKEN is github token
DOCKERHUB_USERNAME is your dockerhub username
DOCKERHUB_TOKEN is your dockerhub token
check out mine:
https://hub.docker.com/r/iskoldt/chuanhuchatgpt/tags
https://github.com/iskoldt-X/ChuanhuChatGPT/pkgs/container/chuanhuchatgpt
需要添加三个secrets，完事儿之后，库的任何更新都会自动启动Docker 镜像更新
> Use github actions to automatically build docker images. amd64 & arm64

- chatgpt - windows.bat
再打开网页的时候也发现了一个小bug，有关于 &nbsp; 与 &lt; 以下是网页的内容：
4. 使用以下命令查看远程分支：
git&nbsp;branch&nbsp;-r
5. 找到要拉取的分支名称，输入以下命令并按回车键：
git&nbsp;checkout&nbsp;-b&nbsp;&lt;new_branch_name&gt;&nbsp;&lt;remote_name&gt;/&lt;branch_name&gt;
其中，&lt;new_branch_name&gt;是要创建的新本地分支的名称，&lt;remote_name&gt;是远程仓库的名称（通常是“origin”），&lt;branch_name&gt;是要拉取的远程分支的名称。
> Add a windows bat file to open chatgpt website quickly.

- ChuanhuChatbot.py
- Dockerfile
- README.md
- requirements.txt
> Tune the Docker image

- README.md
emm，我真的觉得现在的README有点点乱，所以改了一下。
另外，其实troubleshooting可以放进wiki，而不是全放在readme里……另外好像有些也不需要用标题形式啊，不过之前是标题我还是用回标题了。
viewfile: [README.md](https://github.com/Keldos-Li/ChuanhuChatGPT/blob/ec0fb1dba771b12521da35fba4620e3b896d7f02/README.md)
> doc: 修改 README，更加小白友好

- ChuanhuChatbot.py
最后一个chunk中，finish_reason: stop，更新标签状态后再break
> 修复最终finish_reason未更新的问题

- ChuanhuChatbot.py
- utils.py
> feat: 使用log代替print

- ChuanhuChatbot.py
- presets.py
变这样了，chatbot高度固定为700，说不定可以调，不会（
有个问题就是说`status_display`的高度怎么变来变去的啊。
> 大幅美化布局 🗓️ TODO: status_display高度固定

- utils.py
修改了 utill 函数中关于 count_token 函数相关的代码，纠正了token的统计方法
> fixed token count

- ChuanhuChatbot.py
- utils.py
#170 #189 #173 
新增设置apiHost和proxy的功能，待测试
> 添加高级设置：apiHost地址、proxy地址

- README.md
auto TLS HTTPS with Docker nginx proxy
增加一个只使用Docker 就可以实现开启HTTPS 的教程，强烈推荐。
> auto TLS HTTPS with Docker nginx proxy

- ChuanhuChatbot.py
- assets/Kelpy-Codos.js
- assets/custom.js
- overwrites.py
该分支基于 [js](https://github.com/GaiZhenbiao/ChuanhuChatGPT/tree/js) 分支，需要先确定下来 js 如何引入之后再合并。
**Before Merge:**
> feat: 增加代码块复制功能, resolve #241

- .gitignore
- ChuanhuChatbot.py
- modules/llama_func.py
> feature: 优化上传索引文件时空格分割

- ChuanhuChatbot.py
- assets/custom.css
- modules/openai_func.py
- modules/presets.py
> Add API dollar usage and fix style 增加当月API美金使用量

- .gitignore
- ChuanhuChatbot.py
- README.md
- modules/chat_func.py
- modules/openai_func.py
- modules/presets.py
- modules/shared.py
- modules/utils.py
- requirements.txt
可通过配置文件和代码两种方式，在程序启动前预先设定自定义的代理地址和API地址
> feat: 增加程序启动前配置自定义的代理地址和API地址

- .gitignore
- ChuanhuChatbot.py
- config_example.json
- modules/chat_func.py
- modules/config.py
- modules/llama_func.py
- modules/openai_func.py
- modules/pdf_func.py
- modules/utils.py
- requirements.txt
1，使用新的config.json和config.py文件，将config独立出来，便于修改
2，用pdfplumber支持2栏的pdf读取，避免直接使用pypdf2时阅读错位（advanced_pdf_kwargs:two_column=true）
3，proxy的改进：使用with方法
4，log_level的改进：可以在config中自定义更详细的日志规模
> Update 2-column pdf; Update new config type; Update new proxy method

- modules/openai_func.py
Fix: https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/495
> Fix: fix division by zero in usage stats

- modules/openai_func.py
Fix: https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/497
> Fix: fix usage stats when today is first day of the month

- ChuanhuChatbot.py
- README.md
- config_example.json
- modules/chat_func.py
- modules/config.py
- modules/openai_func.py
- modules/utils.py
描述您的pull request所做的更改。
1、增加docker中配置自定义api_host；
2、authflag标记改为判断auth_list的长度而不是判断是否存在uesr这个属性，从而允许配置中存在user这个配置但其对应数组为空的情况；
> 从环境变量中读取配置api_host && authflag改为判断auth_list的长度

- ChuanhuChatbot.py
- assets/custom.js
使用JS实现了输入框的自动填充，通过方向键自动填入历史信息，便于用户使用。
这个是纯前端实现的过程，没有将历史记录保存到后端，将来可以通过加载后端的历史记录，来实现持久化。
> 使用JS实现了输入框通过方向键自动填入历史信息

- modules/chat_func.py
Fix llama 0.5.5 breaking change, we should probably pin a stable version? They are refactoring so frequently
https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/517
> Fix llama 0.5.5 breaking change

- modules/chat_func.py
描述您的pull request所做的更改。
另外请附上相关程序运行时的截图（before & after），以直观地展现您的更改达成的效果。
（如有）请列出与此拉取请求相关的issue。
或者，您可以直接描述您的工作能解决的问题等。
请提供任何其他信息或说明，有助于其他贡献者理解您的更改。
如果您提交的是 draft pull request，也请在这里写明开发进度。例子：
> fix: update chat_func fix int issue

- README.md
- README_en.md
Translate `README.md` to English.
See preview [here](https://github.com/GaiZhenbiao/ChuanhuChatGPT/tree/doc).
resolve #605
Modification and checks still needed.
> doc: translate README to English

- README.md
- README_en.md
- README_ja.md
I have made a Japanese version of README.md. The English version was used as a reference.
I also change the README_en.md and README.md to link Japanse version.
> doc: translate README to Japanese

- modules/config.py
- modules/webui_locale.py
> add default ui lang env

- modules/models/base_model.py
> fix: 修复 Azure OpenAI 回复失败的问题
